export default  {
    "light": {
      "--hsl-primary": "112, 48%, 28%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "0, 0%, 100%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "106, 80%, 79%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "120, 100%, 7%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "101, 13%, 35%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "0, 0%, 100%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "98, 37%, 86%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "106, 38%, 9%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "184, 30%, 31%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "0, 0%, 100%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "184, 60%, 84%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "184, 100%, 7%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "0, 75%, 42%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "0, 0%, 100%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "6, 100%, 92%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "358, 100%, 13%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "69, 64%, 98%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "90, 8%, 10%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "93, 7%, 26%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "93, 5%, 45%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "90, 4%, 18%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    },
    "dark": {
      "--hsl-primary": "107, 51%, 68%",
      "--color-primary": "hsla(var(--hsl-primary), 1)",
      "--hsl-on-primary": "120, 100%, 11%",
      "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
      "--hsl-primary-container": "115, 69%, 19%",
      "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
      "--hsl-on-primary-container": "106, 80%, 79%",
      "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
      "--hsl-info": "98, 19%, 75%",
      "--color-info": "hsla(var(--hsl-info), 1)",
      "--hsl-on-info": "107, 21%, 17%",
      "--color-on-info": "hsla(var(--hsl-on-info), 1)",
      "--hsl-info-container": "105, 15%, 25%",
      "--color-info-container": "hsla(var(--hsl-info-container), 1)",
      "--hsl-on-info-container": "98, 37%, 86%",
      "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
      "--hsl-warning": "184, 36%, 73%",
      "--color-warning": "hsla(var(--hsl-warning), 1)",
      "--hsl-on-warning": "182, 100%, 11%",
      "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
      "--hsl-warning-container": "184, 45%, 22%",
      "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
      "--hsl-on-warning-container": "184, 60%, 84%",
      "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
      "--hsl-danger": "6, 100%, 84%",
      "--color-danger": "hsla(var(--hsl-danger), 1)",
      "--hsl-on-danger": "357, 100%, 21%",
      "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
      "--hsl-danger-container": "356, 100%, 29%",
      "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
      "--hsl-on-danger-container": "6, 100%, 84%",
      "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
      "--hsl-body": "90, 8%, 10%",
      "--color-body": "hsla(var(--hsl-body), 1)",
      "--hsl-text": "69, 11%, 88%",
      "--color-text": "hsla(var(--hsl-text), 1)",
      "--hsl-on-surface-variant": "85, 10%, 76%",
      "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
      "--hsl-outline": "90, 5%, 55%",
      "--color-outline": "hsla(var(--hsl-outline), 1)",
      "--hsl-inverse-surface": "69, 11%, 88%",
      "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)"
    }
  }